#!/usr/bin/env bash

source env_vars_etc

# CROSS COMPILING BASIC SYSTEM TOOLS -----------------------------------------------------------------------------------------------

### make

goto_sources make

./configure                \
    --prefix=/usr          \
    --host=$TARGET_TRIPLET \
    --build=$BUILD_TRIPLET \
    --without-guile

make_install_destdir $SPIDER_ROOT

### coreutils

goto_sources coreutils

./configure                           \
    --prefix=/usr                     \
    --host=$TARGET_TRIPLET            \
    --build=$BUILD_TRIPLET            \
    --enable-install-program=hostname \
    --enable-no-install-program=kill,uptime

make_install_destdir $SPIDER_ROOT

### m4

goto_sources m4

./configure \
    --prefix=/usr   \
    --host=$TARGET_TRIPLET \
    --build=$BUILD_TRIPLET

make_install_destdir $SPIDER_ROOT

### bash

goto_sources bash

./configure                \
    --prefix=/usr          \
    --host=$TARGET_TRIPLET \
    --build=$BUILD_TRIPLET \
    --without-bash-malloc

make_install_destdir $SPIDER_ROOT
sudo ln -sfv bash $SPIDER_ROOT/bin/sh

### sed

goto_sources sed

./configure \
    --prefix=/usr \
    --host=$TARGET_TRIPLET

make_install_destdir $SPIDER_ROOT

### grep

goto_sources grep

./configure \
    --prefix=/usr \
    --host=$TARGET_TRIPLET

make_install_destdir $SPIDER_ROOT

### gawk

goto_sources gawk

sed -i 's/extras//' Makefile.in

./configure \
    --prefix=/usr \
    --host=$TARGET_TRIPLET \
    --build=$BUILD_TRIPLET

make_install_destdir $SPIDER_ROOT

### bison

goto_sources bison

./configure \
    --prefix=/usr \
    --host=$TARGET_TRIPLET \
    --build=$BUILD_TRIPLET

make_install_destdir $SPIDER_ROOT

### perl

goto_sources perl

sh Configure \
    -des                                        \
    -Dprefix=/usr                               \
    -Dvendorprefix=/usr                         \
    -Dprivlib=/usr/lib/perl5/5.34/core_perl     \
    -Darchlib=/usr/lib/perl5/5.34/core_perl     \
    -Dsitelib=/usr/lib/perl5/5.34/site_perl     \
    -Dsitearch=/usr/lib/perl5/5.34/site_perl    \
    -Dvendorlib=/usr/lib/perl5/5.34/vendor_perl \
    -Dvendorarch=/usr/lib/perl5/5.34/vendor_perl

make_install_destdir $SPIDER_ROOT

### grub

goto_sources grub

./configure \
    --prefix=/usr          \
    --host=$TARGET_TRIPLET \
    --build=$BUILD_TRIPLET \
    --sysconfdir=/etc      \
    --disable-efiemu       \
    --disable-werror

make_install_destdir $SPIDER_ROOT

# TODO: install m4, perl and all that other stuff for the linux kernel. oh and
# grub too, you need that too. oh yeah and an init system. anything else? nah.

cd $SOURCES_DIR/..
sudo cp -v finalise_toolchain ../base/root/
