#!/usr/bin/env bash

source env_funcs

# CROSS COMPILING BASIC SYSTEM TOOLS -----------------------------------------------------------------------------------------------

### make

goto_sources make

./configure                \
    --prefix=/usr          \
    --host=$TARGET_TRIPLET \
    --build=$BUILD_TRIPLET \
    --without-guile

make_install_destdir $SPIDER_ROOT

### coreutils

goto_sources coreutils

./configure                           \
    --prefix=/usr                     \
    --host=$TARGET_TRIPLET            \
    --build=$BUILD_TRIPLET            \
    --enable-install-program=hostname \
    --enable-no-install-program=kill,uptime

make_install_destdir $SPIDER_ROOT

### m4

goto_sources m4

./configure \
    --prefix=/usr   \
    --host=$TARGET_TRIPLET \
    --build=$BUILD_TRIPLET

make_install_destdir $SPIDER_ROOT

### bash

goto_sources bash

./configure                \
    --prefix=/usr          \
    --host=$TARGET_TRIPLET \
    --build=$BUILD_TRIPLET \
    --without-bash-malloc

make_install_destdir $SPIDER_ROOT
sudo ln -sfv bash $SPIDER_ROOT/bin/sh

### sed

goto_sources sed

./configure \
    --prefix=/usr \
    --host=$TARGET_TRIPLET

make_install_destdir $SPIDER_ROOT

### grep

goto_sources grep

./configure \
    --prefix=/usr \
    --host=$TARGET_TRIPLET

make_install_destdir $SPIDER_ROOT

### gawk

goto_sources gawk

sed -i 's/extras//' Makefile.in

./configure \
    --prefix=/usr \
    --host=$TARGET_TRIPLET \
    --build=$BUILD_TRIPLET

make_install_destdir $SPIDER_ROOT

sudo cp -v finalise_toolchain ../base/root/
