#!/usr/bin/env bash

source env_vars_etc

echo "==> Cleaning sources..."
run cd $SOURCES_DIR
run sudo rm -rf *

linux_ver=5.15.41
linux_maj_ver=${linux_ver/.*/}
grub_ver=2.06
make_ver=4.3
zlib_ver=1.2.11
perl_ver=5.34.0
perl_maj_ver=${perl_ver/.*/}
ncurses_ver=6.3
flex_ver=2.6.4
bison_ver=3.8.2
m4_ver=latest
gzip_ver=1.11
libelf_ver=latest
bzip_ver=latest
coreutils_ver=9.0
bash_ver=5.1.8
sed_ver=4.8
grep_ver=3.7
gawk_ver=5.1.1
find_ver=4.9.0
tar_ver=latest
autoconf_ver=latest
automake_ver=1.16.5
nano_ver=6.2
nano_maj_ver=${nano_ver/.*/}
xz_ver=5.2.5
python_ver=3.10.4
openrc_ver=0.44.10

declare -A sources

sources[bison_url]="https://ftp.gnu.org/gnu/bison/bison-$bison_ver.tar.xz"
sources[bzip_url]="https://sourceware.org/pub/bzip2/bzip2-$bzip_ver.tar.gz"
sources[flex_url]="https://github.com/westes/flex/files/981163/flex-$flex_ver.tar.gz"
sources[gzip_url]="https://ftp.gnu.org/gnu/gzip/gzip-$gzip_ver.tar.xz"
sources[libelf_url]="https://sourceware.org/elfutils/ftp/elfutils-$libelf_ver.tar.bz2"
sources[linux_url]="https://cdn.kernel.org/pub/linux/kernel/v$linux_maj_ver.x/linux-$linux_ver.tar.xz"
sources[ncurses_url]="https://ftp.gnu.org/gnu/ncurses/ncurses-$ncurses_ver.tar.gz"
sources[perl_url]="https://www.cpan.org/src/$perl_maj_ver.0/perl-$perl_ver.tar.gz"
sources[zlib_url]="https://zlib.net/fossils/zlib-$zlib_ver.tar.gz"
sources[bash_url]="https://ftp.gnu.org/gnu/bash/bash-$bash_ver.tar.gz"
sources[coreutils_url]="https://ftp.gnu.org/gnu/coreutils/coreutils-$coreutils_ver.tar.xz"
sources[grep_url]="https://ftp.gnu.org/gnu/grep/grep-$grep_ver.tar.xz"
sources[grub_url]="https://ftp.gnu.org/gnu/grub/grub-$grub_ver.tar.xz"
sources[m4_url]="https://ftp.gnu.org/gnu/m4/m4-$m4_ver.tar.xz"
sources[make_url]="https://ftp.gnu.org/gnu/make/make-$make_ver.tar.gz"
sources[sed_url]="https://ftp.gnu.org/gnu/sed/sed-$sed_ver.tar.xz"
sources[gawk_url]="https://ftp.gnu.org/gnu/gawk/gawk-$gawk_ver.tar.xz"
sources[find_url]="https://ftp.gnu.org/gnu/findutils/findutils-$find_ver.tar.xz"
sources[tar_url]="https://ftp.gnu.org/gnu/tar/tar-$tar_ver.tar.xz"
sources[autoconf_url]="https://ftp.gnu.org/gnu/autoconf/autoconf-$autoconf_ver.tar.xz"
sources[automake_url]="https://ftp.gnu.org/gnu/automake/automake-$automake_ver.tar.xz"
sources[python_url]="https://www.python.org/ftp/python/$python_ver/Python-$python_ver.tar.xz"
sources[nano_url]="https://www.nano-editor.org/dist/v$nano_maj_ver/nano-$nano_ver.tar.xz"
sources[xz_url]="https://github.com/xz-mirror/xz/archive/refs/tags/v$xz_ver.tar.gz"
sources[openrc_url]="https://github.com/OpenRC/openrc/archive/refs/tags/$openrc_ver.tar.gz"

git clone https://github.com/firasuke/mussel

echo "==> Downloading sources..."
for url in "${sources[@]}"; do
    run curl -L -O "$url"
done

echo "==> Extracting sources..."
for i in *.tar.*; do
    run tar xf "$i"
done
